{{- if .Values.rtorrent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arrmada.componentName" (dict "root" . "component" "rtorrent") }}
  labels:
    {{- include "arrmada.componentLabels" (dict "root" . "component" "rtorrent") | nindent 4 }}
spec:
  type: {{ .Values.rtorrent.service.type }}
  ports:
    - port: {{ .Values.rtorrent.service.floodPort }}
      targetPort: flood
      protocol: TCP
      name: flood
    - port: {{ .Values.rtorrent.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "arrmada.componentSelectorLabels" (dict "root" . "component" "rtorrent") | nindent 4 }}
{{- end }}
