{{- if .Values.prowlarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arrmada.componentName" (dict "root" . "component" "prowlarr") }}
  labels:
    {{- include "arrmada.componentLabels" (dict "root" . "component" "prowlarr") | nindent 4 }}
spec:
  type: {{ .Values.prowlarr.service.type }}
  ports:
    - port: {{ .Values.prowlarr.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arrmada.componentSelectorLabels" (dict "root" . "component" "prowlarr") | nindent 4 }}
{{- end }}
