{{- if not .Values.global.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arrmada.fullname" . }}-secrets
  labels:
    {{- include "arrmada.labels" . | nindent 4 }}
type: Opaque
stringData:
  sonarr-api-key: {{ .Values.global.apiKeys.sonarr | quote }}
  radarr-api-key: {{ .Values.global.apiKeys.radarr | quote }}
  prowlarr-api-key: {{ .Values.global.apiKeys.prowlarr | quote }}
  postgresql-password: {{ .Values.global.postgresql.password | quote }}
{{- end }}
