#!/bin/sh
# prowlarr-export.sh — Export Prowlarr indexer config to a Kubernetes Secret YAML
#
# Usage:
#   ./scripts/prowlarr-export.sh <prowlarr-url> <api-key> [secret-name] [namespace]
#
# Examples:
#   ./scripts/prowlarr-export.sh http://localhost:9696 abc123def456
#   ./scripts/prowlarr-export.sh http://localhost:9696 abc123def456 prowlarr-indexers media
#
# Output is written to stdout. Redirect to a file and apply with kubectl:
#   ./scripts/prowlarr-export.sh http://localhost:9696 abc123def456 > prowlarr-indexers.yaml
#   kubectl apply -n media -f prowlarr-indexers.yaml

set -e

PROWLARR_URL="${1}"
API_KEY="${2}"
SECRET_NAME="${3:-prowlarr-indexers}"
NAMESPACE="${4:-media}"

if [ -z "${PROWLARR_URL}" ] || [ -z "${API_KEY}" ]; then
  echo "Usage: $0 <prowlarr-url> <api-key> [secret-name] [namespace]" >&2
  echo "" >&2
  echo "Examples:" >&2
  echo "  $0 http://localhost:9696 abc123def456" >&2
  echo "  $0 http://localhost:9696 abc123def456 prowlarr-indexers media" >&2
  exit 1
fi

# Check dependencies
for cmd in curl jq; do
  if ! command -v "${cmd}" > /dev/null 2>&1; then
    echo "Error: '${cmd}' is required but not installed." >&2
    exit 1
  fi
done

echo "Fetching indexers from ${PROWLARR_URL}..." >&2

# Fetch indexer list, capturing HTTP status code for actionable error messages
# || true prevents set -e from terminating the script on connection failure,
# allowing the 000 status code check below to produce an actionable error message.
HTTP_RESPONSE=$(curl -s -w "\n%{http_code}" \
  -H "X-Api-Key: ${API_KEY}" \
  "${PROWLARR_URL}/api/v1/indexer" || true)
HTTP_STATUS=$(echo "${HTTP_RESPONSE}" | tail -n1)
# Use sed '$d' instead of head -n -1 for POSIX portability (macOS/BSD compatibility)
INDEXERS=$(echo "${HTTP_RESPONSE}" | sed '$d')

if [ "${HTTP_STATUS}" != "200" ]; then
  case "${HTTP_STATUS}" in
    000) echo "Error: Could not connect to ${PROWLARR_URL}. Is Prowlarr running?" >&2 ;;
    401) echo "Error: Unauthorized (HTTP 401). Check your API key." >&2 ;;
    403) echo "Error: Forbidden (HTTP 403). Check your API key permissions." >&2 ;;
    *)   echo "Error: HTTP ${HTTP_STATUS} from ${PROWLARR_URL}/api/v1/indexer" >&2 ;;
  esac
  exit 1
fi

if [ -z "${INDEXERS}" ]; then
  echo "Error: Empty response from ${PROWLARR_URL}/api/v1/indexer" >&2
  exit 1
fi

COUNT=$(echo "${INDEXERS}" | jq 'length')
echo "Found ${COUNT} indexer(s)" >&2

# Remove id fields (Prowlarr will assign new IDs on import)
# Keep all other fields including sensitive ones (apiKey, username, password)
INDEXERS_CLEAN=$(echo "${INDEXERS}" | jq '[.[] | del(.id)]')

# Base64-encode the JSON for the Secret (tr -d '\n' prevents line-wrapping on non-GNU base64)
INDEXERS_B64=$(echo "${INDEXERS_CLEAN}" | base64 | tr -d '\n')

# Output Kubernetes Secret YAML
cat << EOF
# Generated by prowlarr-export.sh
# Source: ${PROWLARR_URL}
# Indexers: ${COUNT}
#
# IMPORTANT: This Secret contains sensitive data (indexer API keys/passwords).
# Store it securely and do NOT commit it to version control.
#
# To use: apply this Secret and reference it in your values.yaml:
#   prowlarr:
#     config:
#       indexers:
#         existingSecret: ${SECRET_NAME}
#         secretKey: indexers.json
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${NAMESPACE}
type: Opaque
data:
  indexers.json: ${INDEXERS_B64}
EOF

echo "Done. Apply with: kubectl apply -n ${NAMESPACE} -f <output-file>" >&2
