{{- if and .Values.sonarr.enabled .Values.sonarr.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arrmada.componentName" (dict "root" . "component" "sonarr") }}-config
  labels:
    {{- include "arrmada.componentLabels" (dict "root" . "component" "sonarr") | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.sonarr.persistence.config.accessMode }}
  {{- if .Values.sonarr.persistence.config.storageClassName }}
  storageClassName: {{ .Values.sonarr.persistence.config.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sonarr.persistence.config.size | quote }}
{{- end }}
